apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: mariemsouadi12189/task_api:latest   # Replace with your Docker Hub image
          ports:
            - containerPort: 8000
          # Optional: restart policy and resource limits
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
